//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bar.webSercives {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/MobiCarta", ConfigurationName="webSercives.MobiCartaWebServicesSoap")]
    public interface MobiCartaWebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/connect", ReplyAction="*")]
        bool connect();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getRoomsResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getRooms", ReplyAction="*")]
        Bar.webSercives.getRoomsResponse getRooms(Bar.webSercives.getRoomsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getRoom", ReplyAction="*")]
        Bar.webSercives.getRoomResponse getRoom(Bar.webSercives.getRoomRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/saveRoom", ReplyAction="*")]
        Bar.webSercives.saveRoomResponse saveRoom(Bar.webSercives.saveRoomRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getTablesStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getTablesStatus", ReplyAction="*")]
        Bar.webSercives.getTablesStatusResponse getTablesStatus(Bar.webSercives.getTablesStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento room del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/resetJourney", ReplyAction="*")]
        Bar.webSercives.resetJourneyResponse resetJourney(Bar.webSercives.resetJourneyRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getClientStatus", ReplyAction="*")]
        Bar.webSercives.getClientStatusResponse getClientStatus(Bar.webSercives.getClientStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setAllocationTable", ReplyAction="*")]
        Bar.webSercives.setAllocationTableResponse setAllocationTable(Bar.webSercives.setAllocationTableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento setDeallocationTableResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setDeallocationTable", ReplyAction="*")]
        Bar.webSercives.setDeallocationTableResponse setDeallocationTable(Bar.webSercives.setDeallocationTableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setDeallocationClient", ReplyAction="*")]
        Bar.webSercives.setDeallocationClientResponse setDeallocationClient(Bar.webSercives.setDeallocationClientRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/saveProductsList", ReplyAction="*")]
        Bar.webSercives.saveProductsListResponse saveProductsList(Bar.webSercives.saveProductsListRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getProductsResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getProducts", ReplyAction="*")]
        Bar.webSercives.getProductsResponse getProducts(Bar.webSercives.getProductsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getOrdersStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getOrdersStatus", ReplyAction="*")]
        Bar.webSercives.getOrdersStatusResponse getOrdersStatus(Bar.webSercives.getOrdersStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getTableStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getTableStatus", ReplyAction="*")]
        Bar.webSercives.getTableStatusResponse getTableStatus(Bar.webSercives.getTableStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento bill del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/addBillPaid", ReplyAction="*")]
        Bar.webSercives.addBillPaidResponse addBillPaid(Bar.webSercives.addBillPaidRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/addNewOrder", ReplyAction="*")]
        Bar.webSercives.addNewOrderResponse addNewOrder(Bar.webSercives.addNewOrderRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento setOrderStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setOrderStatus", ReplyAction="*")]
        Bar.webSercives.setOrderStatusResponse setOrderStatus(Bar.webSercives.setOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setProductAmount", ReplyAction="*")]
        void setProductAmount(int orderID, int amount);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento setOrderTableResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setOrderTable", ReplyAction="*")]
        Bar.webSercives.setOrderTableResponse setOrderTable(Bar.webSercives.setOrderTableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getTableID", ReplyAction="*")]
        Bar.webSercives.getTableIDResponse getTableID(Bar.webSercives.getTableIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRooms", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getRoomsRequestBody Body;
        
        public getRoomsRequest() {
        }
        
        public getRoomsRequest(Bar.webSercives.getRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getRoomsRequestBody {
        
        public getRoomsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoomsResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getRoomsResponseBody Body;
        
        public getRoomsResponse() {
        }
        
        public getRoomsResponse(Bar.webSercives.getRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRoomsResult;
        
        public getRoomsResponseBody() {
        }
        
        public getRoomsResponseBody(string getRoomsResult) {
            this.getRoomsResult = getRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoom", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getRoomRequestBody Body;
        
        public getRoomRequest() {
        }
        
        public getRoomRequest(Bar.webSercives.getRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getRoomRequestBody() {
        }
        
        public getRoomRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoomResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getRoomResponseBody Body;
        
        public getRoomResponse() {
        }
        
        public getRoomResponse(Bar.webSercives.getRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRoomResult;
        
        public getRoomResponseBody() {
        }
        
        public getRoomResponseBody(string getRoomResult) {
            this.getRoomResult = getRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveRoom", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.saveRoomRequestBody Body;
        
        public saveRoomRequest() {
        }
        
        public saveRoomRequest(Bar.webSercives.saveRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class saveRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public saveRoomRequestBody() {
        }
        
        public saveRoomRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveRoomResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.saveRoomResponseBody Body;
        
        public saveRoomResponse() {
        }
        
        public saveRoomResponse(Bar.webSercives.saveRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class saveRoomResponseBody {
        
        public saveRoomResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTablesStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTablesStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getTablesStatusRequestBody Body;
        
        public getTablesStatusRequest() {
        }
        
        public getTablesStatusRequest(Bar.webSercives.getTablesStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getTablesStatusRequestBody {
        
        public getTablesStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTablesStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTablesStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getTablesStatusResponseBody Body;
        
        public getTablesStatusResponse() {
        }
        
        public getTablesStatusResponse(Bar.webSercives.getTablesStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTablesStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTablesStatusResult;
        
        public getTablesStatusResponseBody() {
        }
        
        public getTablesStatusResponseBody(string getTablesStatusResult) {
            this.getTablesStatusResult = getTablesStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetJourneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetJourney", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.resetJourneyRequestBody Body;
        
        public resetJourneyRequest() {
        }
        
        public resetJourneyRequest(Bar.webSercives.resetJourneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class resetJourneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string room;
        
        public resetJourneyRequestBody() {
        }
        
        public resetJourneyRequestBody(string room) {
            this.room = room;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetJourneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetJourneyResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.resetJourneyResponseBody Body;
        
        public resetJourneyResponse() {
        }
        
        public resetJourneyResponse(Bar.webSercives.resetJourneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class resetJourneyResponseBody {
        
        public resetJourneyResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getClientStatusRequestBody Body;
        
        public getClientStatusRequest() {
        }
        
        public getClientStatusRequest(Bar.webSercives.getClientStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getClientStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string surname;
        
        public getClientStatusRequestBody() {
        }
        
        public getClientStatusRequestBody(string dni, string name, string surname) {
            this.dni = dni;
            this.name = name;
            this.surname = surname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getClientStatusResponseBody Body;
        
        public getClientStatusResponse() {
        }
        
        public getClientStatusResponse(Bar.webSercives.getClientStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getClientStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getClientStatusResult;
        
        public getClientStatusResponseBody() {
        }
        
        public getClientStatusResponseBody(int getClientStatusResult) {
            this.getClientStatusResult = getClientStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setAllocationTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setAllocationTable", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setAllocationTableRequestBody Body;
        
        public setAllocationTableRequest() {
        }
        
        public setAllocationTableRequest(Bar.webSercives.setAllocationTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setAllocationTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int guests;
        
        public setAllocationTableRequestBody() {
        }
        
        public setAllocationTableRequestBody(string dni, int tableID, int guests) {
            this.dni = dni;
            this.tableID = tableID;
            this.guests = guests;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setAllocationTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setAllocationTableResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setAllocationTableResponseBody Body;
        
        public setAllocationTableResponse() {
        }
        
        public setAllocationTableResponse(Bar.webSercives.setAllocationTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setAllocationTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setAllocationTableResult;
        
        public setAllocationTableResponseBody() {
        }
        
        public setAllocationTableResponseBody(string setAllocationTableResult) {
            this.setAllocationTableResult = setAllocationTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationTable", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setDeallocationTableRequestBody Body;
        
        public setDeallocationTableRequest() {
        }
        
        public setDeallocationTableRequest(Bar.webSercives.setDeallocationTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tableID;
        
        public setDeallocationTableRequestBody() {
        }
        
        public setDeallocationTableRequestBody(int tableID) {
            this.tableID = tableID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationTableResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setDeallocationTableResponseBody Body;
        
        public setDeallocationTableResponse() {
        }
        
        public setDeallocationTableResponse(Bar.webSercives.setDeallocationTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setDeallocationTableResult;
        
        public setDeallocationTableResponseBody() {
        }
        
        public setDeallocationTableResponseBody(string setDeallocationTableResult) {
            this.setDeallocationTableResult = setDeallocationTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationClient", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setDeallocationClientRequestBody Body;
        
        public setDeallocationClientRequest() {
        }
        
        public setDeallocationClientRequest(Bar.webSercives.setDeallocationClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        public setDeallocationClientRequestBody() {
        }
        
        public setDeallocationClientRequestBody(string dni) {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationClientResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setDeallocationClientResponseBody Body;
        
        public setDeallocationClientResponse() {
        }
        
        public setDeallocationClientResponse(Bar.webSercives.setDeallocationClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setDeallocationClientResult;
        
        public setDeallocationClientResponseBody() {
        }
        
        public setDeallocationClientResponseBody(string setDeallocationClientResult) {
            this.setDeallocationClientResult = setDeallocationClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveProductsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveProductsList", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.saveProductsListRequestBody Body;
        
        public saveProductsListRequest() {
        }
        
        public saveProductsListRequest(Bar.webSercives.saveProductsListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class saveProductsListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public saveProductsListRequestBody() {
        }
        
        public saveProductsListRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveProductsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveProductsListResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.saveProductsListResponseBody Body;
        
        public saveProductsListResponse() {
        }
        
        public saveProductsListResponse(Bar.webSercives.saveProductsListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class saveProductsListResponseBody {
        
        public saveProductsListResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProducts", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getProductsRequestBody Body;
        
        public getProductsRequest() {
        }
        
        public getProductsRequest(Bar.webSercives.getProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getProductsRequestBody {
        
        public getProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductsResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getProductsResponseBody Body;
        
        public getProductsResponse() {
        }
        
        public getProductsResponse(Bar.webSercives.getProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getProductsResult;
        
        public getProductsResponseBody() {
        }
        
        public getProductsResponseBody(string getProductsResult) {
            this.getProductsResult = getProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrdersStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrdersStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getOrdersStatusRequestBody Body;
        
        public getOrdersStatusRequest() {
        }
        
        public getOrdersStatusRequest(Bar.webSercives.getOrdersStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getOrdersStatusRequestBody {
        
        public getOrdersStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrdersStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrdersStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getOrdersStatusResponseBody Body;
        
        public getOrdersStatusResponse() {
        }
        
        public getOrdersStatusResponse(Bar.webSercives.getOrdersStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getOrdersStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getOrdersStatusResult;
        
        public getOrdersStatusResponseBody() {
        }
        
        public getOrdersStatusResponseBody(string getOrdersStatusResult) {
            this.getOrdersStatusResult = getOrdersStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getTableStatusRequestBody Body;
        
        public getTableStatusRequest() {
        }
        
        public getTableStatusRequest(Bar.webSercives.getTableStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tableID;
        
        public getTableStatusRequestBody() {
        }
        
        public getTableStatusRequestBody(int tableID) {
            this.tableID = tableID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getTableStatusResponseBody Body;
        
        public getTableStatusResponse() {
        }
        
        public getTableStatusResponse(Bar.webSercives.getTableStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTableStatusResult;
        
        public getTableStatusResponseBody() {
        }
        
        public getTableStatusResponseBody(string getTableStatusResult) {
            this.getTableStatusResult = getTableStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBillPaidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addBillPaid", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.addBillPaidRequestBody Body;
        
        public addBillPaidRequest() {
        }
        
        public addBillPaidRequest(Bar.webSercives.addBillPaidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class addBillPaidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bill;
        
        public addBillPaidRequestBody() {
        }
        
        public addBillPaidRequestBody(string bill) {
            this.bill = bill;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBillPaidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addBillPaidResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.addBillPaidResponseBody Body;
        
        public addBillPaidResponse() {
        }
        
        public addBillPaidResponse(Bar.webSercives.addBillPaidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class addBillPaidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addBillPaidResult;
        
        public addBillPaidResponseBody() {
        }
        
        public addBillPaidResponseBody(string addBillPaidResult) {
            this.addBillPaidResult = addBillPaidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNewOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNewOrder", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.addNewOrderRequestBody Body;
        
        public addNewOrderRequest() {
        }
        
        public addNewOrderRequest(Bar.webSercives.addNewOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class addNewOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public addNewOrderRequestBody() {
        }
        
        public addNewOrderRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNewOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNewOrderResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.addNewOrderResponseBody Body;
        
        public addNewOrderResponse() {
        }
        
        public addNewOrderResponse(Bar.webSercives.addNewOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class addNewOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addNewOrderResult;
        
        public addNewOrderResponseBody() {
        }
        
        public addNewOrderResponseBody(string addNewOrderResult) {
            this.addNewOrderResult = addNewOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setOrderStatusRequestBody Body;
        
        public setOrderStatusRequest() {
        }
        
        public setOrderStatusRequest(Bar.webSercives.setOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int status;
        
        public setOrderStatusRequestBody() {
        }
        
        public setOrderStatusRequestBody(int orderID, int status) {
            this.orderID = orderID;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setOrderStatusResponseBody Body;
        
        public setOrderStatusResponse() {
        }
        
        public setOrderStatusResponse(Bar.webSercives.setOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setOrderStatusResult;
        
        public setOrderStatusResponseBody() {
        }
        
        public setOrderStatusResponseBody(string setOrderStatusResult) {
            this.setOrderStatusResult = setOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderTable", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setOrderTableRequestBody Body;
        
        public setOrderTableRequest() {
        }
        
        public setOrderTableRequest(Bar.webSercives.setOrderTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setOrderTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tableID;
        
        public setOrderTableRequestBody() {
        }
        
        public setOrderTableRequestBody(int orderID, int tableID) {
            this.orderID = orderID;
            this.tableID = tableID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderTableResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.setOrderTableResponseBody Body;
        
        public setOrderTableResponse() {
        }
        
        public setOrderTableResponse(Bar.webSercives.setOrderTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setOrderTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setOrderTableResult;
        
        public setOrderTableResponseBody() {
        }
        
        public setOrderTableResponseBody(string setOrderTableResult) {
            this.setOrderTableResult = setOrderTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableID", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getTableIDRequestBody Body;
        
        public getTableIDRequest() {
        }
        
        public getTableIDRequest(Bar.webSercives.getTableIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        public getTableIDRequestBody() {
        }
        
        public getTableIDRequestBody(string dni) {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableIDResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Bar.webSercives.getTableIDResponseBody Body;
        
        public getTableIDResponse() {
        }
        
        public getTableIDResponse(Bar.webSercives.getTableIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getTableIDResult;
        
        public getTableIDResponseBody() {
        }
        
        public getTableIDResponseBody(int getTableIDResult) {
            this.getTableIDResult = getTableIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MobiCartaWebServicesSoapChannel : Bar.webSercives.MobiCartaWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobiCartaWebServicesSoapClient : System.ServiceModel.ClientBase<Bar.webSercives.MobiCartaWebServicesSoap>, Bar.webSercives.MobiCartaWebServicesSoap {
        
        public MobiCartaWebServicesSoapClient() {
        }
        
        public MobiCartaWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobiCartaWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobiCartaWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobiCartaWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool connect() {
            return base.Channel.connect();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.getRoomsResponse Bar.webSercives.MobiCartaWebServicesSoap.getRooms(Bar.webSercives.getRoomsRequest request) {
            return base.Channel.getRooms(request);
        }
        
        public string getRooms() {
            Bar.webSercives.getRoomsRequest inValue = new Bar.webSercives.getRoomsRequest();
            inValue.Body = new Bar.webSercives.getRoomsRequestBody();
            Bar.webSercives.getRoomsResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).getRooms(inValue);
            return retVal.Body.getRoomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.getRoomResponse Bar.webSercives.MobiCartaWebServicesSoap.getRoom(Bar.webSercives.getRoomRequest request) {
            return base.Channel.getRoom(request);
        }
        
        public string getRoom(string name) {
            Bar.webSercives.getRoomRequest inValue = new Bar.webSercives.getRoomRequest();
            inValue.Body = new Bar.webSercives.getRoomRequestBody();
            inValue.Body.name = name;
            Bar.webSercives.getRoomResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).getRoom(inValue);
            return retVal.Body.getRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.saveRoomResponse Bar.webSercives.MobiCartaWebServicesSoap.saveRoom(Bar.webSercives.saveRoomRequest request) {
            return base.Channel.saveRoom(request);
        }
        
        public void saveRoom(string xml) {
            Bar.webSercives.saveRoomRequest inValue = new Bar.webSercives.saveRoomRequest();
            inValue.Body = new Bar.webSercives.saveRoomRequestBody();
            inValue.Body.xml = xml;
            Bar.webSercives.saveRoomResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).saveRoom(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.getTablesStatusResponse Bar.webSercives.MobiCartaWebServicesSoap.getTablesStatus(Bar.webSercives.getTablesStatusRequest request) {
            return base.Channel.getTablesStatus(request);
        }
        
        public string getTablesStatus() {
            Bar.webSercives.getTablesStatusRequest inValue = new Bar.webSercives.getTablesStatusRequest();
            inValue.Body = new Bar.webSercives.getTablesStatusRequestBody();
            Bar.webSercives.getTablesStatusResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).getTablesStatus(inValue);
            return retVal.Body.getTablesStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.resetJourneyResponse Bar.webSercives.MobiCartaWebServicesSoap.resetJourney(Bar.webSercives.resetJourneyRequest request) {
            return base.Channel.resetJourney(request);
        }
        
        public void resetJourney(string room) {
            Bar.webSercives.resetJourneyRequest inValue = new Bar.webSercives.resetJourneyRequest();
            inValue.Body = new Bar.webSercives.resetJourneyRequestBody();
            inValue.Body.room = room;
            Bar.webSercives.resetJourneyResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).resetJourney(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.getClientStatusResponse Bar.webSercives.MobiCartaWebServicesSoap.getClientStatus(Bar.webSercives.getClientStatusRequest request) {
            return base.Channel.getClientStatus(request);
        }
        
        public int getClientStatus(string dni, string name, string surname) {
            Bar.webSercives.getClientStatusRequest inValue = new Bar.webSercives.getClientStatusRequest();
            inValue.Body = new Bar.webSercives.getClientStatusRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            Bar.webSercives.getClientStatusResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).getClientStatus(inValue);
            return retVal.Body.getClientStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.setAllocationTableResponse Bar.webSercives.MobiCartaWebServicesSoap.setAllocationTable(Bar.webSercives.setAllocationTableRequest request) {
            return base.Channel.setAllocationTable(request);
        }
        
        public string setAllocationTable(string dni, int tableID, int guests) {
            Bar.webSercives.setAllocationTableRequest inValue = new Bar.webSercives.setAllocationTableRequest();
            inValue.Body = new Bar.webSercives.setAllocationTableRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.tableID = tableID;
            inValue.Body.guests = guests;
            Bar.webSercives.setAllocationTableResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).setAllocationTable(inValue);
            return retVal.Body.setAllocationTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.setDeallocationTableResponse Bar.webSercives.MobiCartaWebServicesSoap.setDeallocationTable(Bar.webSercives.setDeallocationTableRequest request) {
            return base.Channel.setDeallocationTable(request);
        }
        
        public string setDeallocationTable(int tableID) {
            Bar.webSercives.setDeallocationTableRequest inValue = new Bar.webSercives.setDeallocationTableRequest();
            inValue.Body = new Bar.webSercives.setDeallocationTableRequestBody();
            inValue.Body.tableID = tableID;
            Bar.webSercives.setDeallocationTableResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).setDeallocationTable(inValue);
            return retVal.Body.setDeallocationTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.setDeallocationClientResponse Bar.webSercives.MobiCartaWebServicesSoap.setDeallocationClient(Bar.webSercives.setDeallocationClientRequest request) {
            return base.Channel.setDeallocationClient(request);
        }
        
        public string setDeallocationClient(string dni) {
            Bar.webSercives.setDeallocationClientRequest inValue = new Bar.webSercives.setDeallocationClientRequest();
            inValue.Body = new Bar.webSercives.setDeallocationClientRequestBody();
            inValue.Body.dni = dni;
            Bar.webSercives.setDeallocationClientResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).setDeallocationClient(inValue);
            return retVal.Body.setDeallocationClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.saveProductsListResponse Bar.webSercives.MobiCartaWebServicesSoap.saveProductsList(Bar.webSercives.saveProductsListRequest request) {
            return base.Channel.saveProductsList(request);
        }
        
        public void saveProductsList(string xml) {
            Bar.webSercives.saveProductsListRequest inValue = new Bar.webSercives.saveProductsListRequest();
            inValue.Body = new Bar.webSercives.saveProductsListRequestBody();
            inValue.Body.xml = xml;
            Bar.webSercives.saveProductsListResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).saveProductsList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.getProductsResponse Bar.webSercives.MobiCartaWebServicesSoap.getProducts(Bar.webSercives.getProductsRequest request) {
            return base.Channel.getProducts(request);
        }
        
        public string getProducts() {
            Bar.webSercives.getProductsRequest inValue = new Bar.webSercives.getProductsRequest();
            inValue.Body = new Bar.webSercives.getProductsRequestBody();
            Bar.webSercives.getProductsResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).getProducts(inValue);
            return retVal.Body.getProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.getOrdersStatusResponse Bar.webSercives.MobiCartaWebServicesSoap.getOrdersStatus(Bar.webSercives.getOrdersStatusRequest request) {
            return base.Channel.getOrdersStatus(request);
        }
        
        public string getOrdersStatus() {
            Bar.webSercives.getOrdersStatusRequest inValue = new Bar.webSercives.getOrdersStatusRequest();
            inValue.Body = new Bar.webSercives.getOrdersStatusRequestBody();
            Bar.webSercives.getOrdersStatusResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).getOrdersStatus(inValue);
            return retVal.Body.getOrdersStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.getTableStatusResponse Bar.webSercives.MobiCartaWebServicesSoap.getTableStatus(Bar.webSercives.getTableStatusRequest request) {
            return base.Channel.getTableStatus(request);
        }
        
        public string getTableStatus(int tableID) {
            Bar.webSercives.getTableStatusRequest inValue = new Bar.webSercives.getTableStatusRequest();
            inValue.Body = new Bar.webSercives.getTableStatusRequestBody();
            inValue.Body.tableID = tableID;
            Bar.webSercives.getTableStatusResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).getTableStatus(inValue);
            return retVal.Body.getTableStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.addBillPaidResponse Bar.webSercives.MobiCartaWebServicesSoap.addBillPaid(Bar.webSercives.addBillPaidRequest request) {
            return base.Channel.addBillPaid(request);
        }
        
        public string addBillPaid(string bill) {
            Bar.webSercives.addBillPaidRequest inValue = new Bar.webSercives.addBillPaidRequest();
            inValue.Body = new Bar.webSercives.addBillPaidRequestBody();
            inValue.Body.bill = bill;
            Bar.webSercives.addBillPaidResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).addBillPaid(inValue);
            return retVal.Body.addBillPaidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.addNewOrderResponse Bar.webSercives.MobiCartaWebServicesSoap.addNewOrder(Bar.webSercives.addNewOrderRequest request) {
            return base.Channel.addNewOrder(request);
        }
        
        public string addNewOrder(string xml) {
            Bar.webSercives.addNewOrderRequest inValue = new Bar.webSercives.addNewOrderRequest();
            inValue.Body = new Bar.webSercives.addNewOrderRequestBody();
            inValue.Body.xml = xml;
            Bar.webSercives.addNewOrderResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).addNewOrder(inValue);
            return retVal.Body.addNewOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.setOrderStatusResponse Bar.webSercives.MobiCartaWebServicesSoap.setOrderStatus(Bar.webSercives.setOrderStatusRequest request) {
            return base.Channel.setOrderStatus(request);
        }
        
        public string setOrderStatus(int orderID, int status) {
            Bar.webSercives.setOrderStatusRequest inValue = new Bar.webSercives.setOrderStatusRequest();
            inValue.Body = new Bar.webSercives.setOrderStatusRequestBody();
            inValue.Body.orderID = orderID;
            inValue.Body.status = status;
            Bar.webSercives.setOrderStatusResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).setOrderStatus(inValue);
            return retVal.Body.setOrderStatusResult;
        }
        
        public void setProductAmount(int orderID, int amount) {
            base.Channel.setProductAmount(orderID, amount);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.setOrderTableResponse Bar.webSercives.MobiCartaWebServicesSoap.setOrderTable(Bar.webSercives.setOrderTableRequest request) {
            return base.Channel.setOrderTable(request);
        }
        
        public string setOrderTable(int orderID, int tableID) {
            Bar.webSercives.setOrderTableRequest inValue = new Bar.webSercives.setOrderTableRequest();
            inValue.Body = new Bar.webSercives.setOrderTableRequestBody();
            inValue.Body.orderID = orderID;
            inValue.Body.tableID = tableID;
            Bar.webSercives.setOrderTableResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).setOrderTable(inValue);
            return retVal.Body.setOrderTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bar.webSercives.getTableIDResponse Bar.webSercives.MobiCartaWebServicesSoap.getTableID(Bar.webSercives.getTableIDRequest request) {
            return base.Channel.getTableID(request);
        }
        
        public int getTableID(string dni) {
            Bar.webSercives.getTableIDRequest inValue = new Bar.webSercives.getTableIDRequest();
            inValue.Body = new Bar.webSercives.getTableIDRequestBody();
            inValue.Body.dni = dni;
            Bar.webSercives.getTableIDResponse retVal = ((Bar.webSercives.MobiCartaWebServicesSoap)(this)).getTableID(inValue);
            return retVal.Body.getTableIDResult;
        }
    }
}
